### ISSUE TITLE
`/features` appears as a valid suggestion 

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-dev-chrome-launcher#12]
1. Visit https://github.com/features/codespaces
2. Type `code features` into browser omnibox with this extension installed 
3. :bug: `features/codespaces` shows up

**Comment by joyceerhl** [comment]
Verification: sideload this extension following https://github.com/microsoft/vscode-dev-chrome-launcher/blob/main/CONTRIBUTING.md#development, then follow the repro steps above

**Comment by hediet** [comment]
`features/codespaces` does not show up, but I'm not sure I'm doing the right thing:

![image](https://user-images.githubusercontent.com/2931520/198323616-e6d6d54f-074b-4a31-af0c-54149e78760a.png)

**Comment by joyceerhl** [comment]
👍 that's the scenario, thank you for verifying!
