### ISSUE TITLE
Allow the button to work on Azure Repos

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-dev-chrome-launcher#24]
I click on the button in the address bar and it shows `insiders.vscode.dev` instead of the Azure Repos link.

🙏 please let me click the button while looking at an Azure Repo and have it work just like the `.`.

**Comment by joyceerhl** [comment]
Verification steps: https://github.com/microsoft/vscode-dev-chrome-launcher/blob/main/CONTRIBUTING.md#development
